# Generated by Django 5.0.6 on 2024-07-06 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Messenger_API', '0002_user_first_name_user_last_name_user_profile_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_id',
            field=models.CharField(default=None, max_length=10, null=True, unique=True),
        ),
    ]
