# Generated by Django 5.0.6 on 2024-07-07 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Messenger_API', '0003_alter_user_profile_id'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='UserModel',
        ),
    ]
